import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Header } from "@/components/Header";
import { ReportView } from "@/components/ReportView";
import demoReport from "@/data/demo-cursor.json";
import type { RedditReport } from "@readdit/core";

export const metadata = {
  title: "Example report - Readdit",
};

export default function DemoPage() {
  const report = demoReport as unknown as RedditReport;

  return (
    <>
      <Header />
      <main className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-14">
        <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
          <div>
            <p className="font-mono text-xs uppercase text-accent">Sample report</p>
            <h1 className="mt-2 text-2xl font-semibold text-ink">
              What does Reddit think about Cursor?
            </h1>
          </div>
          <Link
            href="/playground"
            className="inline-flex items-center gap-2 bg-ink px-4 py-2.5 text-sm font-semibold text-canvas hover:bg-accent"
          >
            Run your own
            <ArrowRight className="h-4 w-4" aria-hidden="true" />
          </Link>
        </div>
        <p className="mb-8 border border-neutral/40 bg-neutral/10 px-4 py-3 text-xs leading-5 text-muted">
          This bundled sample was generated by the deterministic mock provider for UI review. It
          does not claim to be live Reddit evidence. Use the playground&apos;s source search for real
          DuckDuckGo/Reddit retrieval without an AI key.
        </p>

        <div className="border border-border bg-surface p-4 sm:p-6">
          <ReportView report={report} />
        </div>
      </main>
    </>
  );
}
