import type {
  AnalysisInput,
  AnalysisProvider,
  CompareReport,
  Evidence,
  NormalizedDiscussion,
  RedditReport,
  SentimentLabel,
} from "../types.js";

const NEGATIVE_WORDS = ["problem", "issue", "bug", "disappoint", "broken", "worst", "regret", "annoy", "expensive", "pricing"];
const POSITIVE_WORDS = ["love", "great", "solid", "fast", "productive", "worth", "good", "responsive"];

function classify(text: string): "positive" | "negative" | "neutral" {
  const t = text.toLowerCase();
  const neg = NEGATIVE_WORDS.some((w) => t.includes(w));
  const pos = POSITIVE_WORDS.some((w) => t.includes(w));
  if (neg && !pos) return "negative";
  if (pos && !neg) return "positive";
  return "neutral";
}

function toEvidence(discussions: NormalizedDiscussion[], claim: string): Evidence {
  return {
    claim,
    sources: discussions.slice(0, 2).map((d) => ({
      title: d.title,
      url: d.url,
      subreddit: d.subreddit,
      author: d.author,
      timestamp: d.timestamp,
      score: d.score,
    })),
  };
}

/**
 * Deterministic, keyword-based "analysis" that never calls an LLM — used
 * for local development and tests (READDIT_MOCK_PROVIDERS=1) so the full
 * pipeline (search → rank → synthesize → render) can be exercised without
 * spending OpenRouter budget. Evidence still points at real discussion
 * objects (from MockSearchProvider or a live search), never fabricated URLs.
 */
export class MockAnalysisProvider implements AnalysisProvider {
  readonly name = "mock";
  readonly model = "mock/keyword-classifier";

  async analyze(input: AnalysisInput): Promise<RedditReport> {
    const { discussions } = input;
    const positives = discussions.filter((d) => classify(`${d.title} ${d.text ?? ""}`) === "positive");
    const negatives = discussions.filter((d) => classify(`${d.title} ${d.text ?? ""}`) === "negative");

    const score = Math.round(
      50 + ((positives.length - negatives.length) / Math.max(discussions.length, 1)) * 50
    );
    const label = scoreToLabel(score);

    const subredditCounts = new Map<string, number>();
    for (const d of discussions) {
      const key = d.subreddit ?? "unknown";
      subredditCounts.set(key, (subredditCounts.get(key) ?? 0) + 1);
    }
    const subreddits = Array.from(subredditCounts.entries())
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count);

    return {
      query: input.query,
      intent: input.intent,
      summary: `[MOCK] Based on ${discussions.length} retrieved discussions, sentiment toward "${input.query}" leans ${label.replace("_", " ")}. This is a deterministic mock report — no LLM was called.`,
      keyTakeaways: [
        `${positives.length} discussions read as positive, ${negatives.length} as negative (keyword heuristic).`,
        `Coverage spans ${subreddits.length} subreddit(s).`,
      ],
      sentiment: { score: Math.max(0, Math.min(100, score)), label, confidence: 0.4 },
      praise: positives.slice(0, 5).map((d) => d.title),
      complaints: negatives.slice(0, 5).map((d) => d.title),
      featureRequests: discussions
        .filter((d) => /wish|feature request|would be nice|missing/i.test(`${d.title} ${d.text ?? ""}`))
        .slice(0, 5)
        .map((d) => d.title),
      themes: subreddits.slice(0, 4).map((s) => ({
        name: `Discussion in r/${s.name}`,
        description: `${s.count} related discussion(s) found here.`,
        frequency: s.count,
      })),
      comparisons: [],
      switchingReasons: [],
      evidence: [
        toEvidence(positives.length ? positives : discussions, "Representative positive/neutral discussion"),
        toEvidence(negatives.length ? negatives : discussions.slice(-2), "Representative negative discussion"),
      ].filter((e) => e.sources.length > 0),
      sourceCount: discussions.length,
      subreddits,
      confidence: {
        level: discussions.length >= 20 ? "medium" : "low",
        sourceCount: discussions.length,
        subredditCount: subreddits.length,
        reasoning: "Mock provider — confidence is illustrative only.",
      },
      limitations: [
        "This report was generated by the mock analysis provider (no LLM call was made).",
        "Reddit users are not a statistically representative sample of the entire market.",
      ],
      generatedAt: new Date().toISOString(),
      model: this.model,
      cached: false,
    };
  }

  async compare(
    input: AnalysisInput & { discussionsB: NormalizedDiscussion[] }
  ): Promise<CompareReport> {
    const a = await this.analyze(input);
    const b = await this.analyze({ ...input, discussions: input.discussionsB, query: input.secondaryTopic ?? "B" });

    return {
      query: `${input.query} vs ${input.secondaryTopic ?? "B"}`,
      productA: input.query,
      productB: input.secondaryTopic ?? "B",
      summary: `[MOCK] Comparing ${input.query} and ${input.secondaryTopic}.`,
      overallSentiment: { a: a.sentiment, b: b.sentiment },
      strengthsA: a.praise,
      strengthsB: b.praise,
      complaintsA: a.complaints,
      complaintsB: b.complaints,
      commonThemes: [],
      switching: [],
      evidence: [...a.evidence, ...b.evidence],
      sourceCount: a.sourceCount + b.sourceCount,
      subreddits: [...a.subreddits, ...b.subreddits],
      limitations: a.limitations,
      generatedAt: new Date().toISOString(),
      model: this.model,
      cached: false,
    };
  }
}

function scoreToLabel(score: number): SentimentLabel {
  if (score >= 80) return "very_positive";
  if (score >= 60) return "positive";
  if (score >= 40) return "mixed";
  if (score >= 20) return "negative";
  return "very_negative";
}
